Revert "ssh connection supports ipv6"
This reverts commit 967e89eab65e06d37aec105231a69f572cb53acf.

No idea how this was merged, sorry. Any connection_info.address can be
a domain name, not a resolved IP addr, at that point.

We get a straight

    Traceback (most recent call Last):
    File "<...>\lisa-overlake\lisa\lisa\util\shell.py", line 89, in wait_tcp_port_ready
    result = tcp_socket.connect_ex((address, port))
    socket.gaierror: [Errno 11001] getaddrinfo failed

with that.