Upgrade "azure-mgmt-compute" to "30.5.0"
IntelTDX OS disk captures are failing with below error:

azure.core.exceptions.HttpResponseError: (BadRequest) Minimum api-version of 2023-10-02 required to use ReadSecure or WriteSecure SAS access.
Code: BadRequest
Message: Minimum api-version of 2023-10-02 required to use ReadSecure or WriteSecure SAS access.

Upgrading "azure-mgmt-compute" to "30.5.0" fixed this issue.